# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_album_author_book_feedback_message_news_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='feedback',
            name='phone_no',
            field=models.IntegerField(default='0', max_length=10),
        ),
    ]
