# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20170906_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone_no',
            field=models.IntegerField(default='0'),
        ),
    ]
